  @Test
  public void testErrorAfter() throws Exception {
    type = SoreType.ERROR;
    where = SorePoint.AFTER;
    checkTestName(runAndReturnSyserr(), Nested.class.getSimpleName() + ".test");
  }

