  /**
   * Tests that {@link #expectThrows} behaves correctly when the Runnable contains an assertion that
   * does not pass: by allowing that assertion to propogate and <code>FAIL</code> the test.
   */
  public void testNestedFail() {
    final AtomicBoolean ran = new AtomicBoolean(false);
    AssertionError caught = null;
    try {
      final IOException returned =
          expectThrows(
              IOException.class,
              () -> {
                ran.getAndSet(true);
                fail("this failure should propogate");
              });
      fail("must not complete"); // NOTE: we don't use expectThrows to test expectThrows
    } catch (AssertionError ae) {
      caught = ae;
    }
    assertTrue(ran.get());
    assertNotNull(caught);
    assertEquals("this failure should propogate", caught.getMessage());
  }

