  @Test
  public void testFailureAfterClass() throws Exception {
    type = SoreType.FAILURE;
    where = SorePoint.AFTER_CLASS;
    Assert.assertTrue(runAndReturnSyserr().contains("NOTE: reproduce with:"));
  }

