  @Test
  public void testErrorAfterClass() throws Exception {
    type = SoreType.ERROR;
    where = SorePoint.AFTER_CLASS;
    Assert.assertTrue(runAndReturnSyserr().contains("NOTE: reproduce with:"));
  }

