  @Test
  public void testFailureAfter() throws Exception {
    type = SoreType.FAILURE;
    where = SorePoint.AFTER;
    checkTestName(runAndReturnSyserr(), Nested.class.getSimpleName() + ".test");
  }

