  @Test(expected = AlreadySetException.class)
  public void testSettingCtor() throws Exception {
    SetOnce<Integer> set = new SetOnce<>(5);
    assertEquals(5, set.get().intValue());
    set.set(7);
  }

