  @Test(expected = AlreadySetException.class)
  public void testSetOnce() throws Exception {
    SetOnce<Integer> set = new SetOnce<>();
    set.set(5);
    assertEquals(5, set.get().intValue());
    set.set(7);
  }

