  private void expectFail(ThrowingRunnable runnable) throws Exception {
    for (int i = 0; i < 20; i++) {
      try {
        runnable.run();
      } catch (Throwable throwable) {
        return;
      }
      Thread.sleep(100);
    }
    fail("should have failed with an exception");
  }

