  public void testBreak() throws Exception {
    doTest("break");
  }

